<h2 id="buttons">Buttons</h2>

<span class="mt-4 d-block text-muted text-uppercase">Primary Buttons</span>
<hr class="mt-0" />

<div class="row">
    <div class="col-12 col-md-6 col-lg-4">
        <button class="btn btn-primary btn-block btn-lg" type="button">Vai al Carrello</button>
        <span class="d-block mt-1 text-muted">Enabled CTA XL</span>
    </div>
    <div class="col-12 col-md-6 col-lg-4">
        <button class="btn btn-primary btn-block btn-lg" type="button" disabled>Vai al Carrello</button>
        <span class="d-block mt-1 text-muted">Disabled CTA XL</span>
    </div>
</div>
<div class="row my-4">
    <div class="col-12 col-md-6 col-lg-4">
        <button class="btn btn-primary btn-block" type="button">Scopri subito</button>
        <span class="d-block mt-1 text-muted">Enabled CTA L</span>
    </div>
    <div class="col-12 col-md-6 col-lg-4">
        <button class="btn btn-primary btn-block" type="button" disabled>Scopri subito</button>
        <span class="d-block mt-1 text-muted">Disabled CTA L</span>
    </div>
</div>
<div class="row my-4">
    <div class="col-4 col-md-3 col-lg-2">
        <button class="btn btn-sm btn-primary" type="button">Acquista</button>
        <span class="d-block mt-1 text-muted">Enabled CTA S</span>
    </div>
    <div class="col-4 col-md-3 col-lg-2">
        <button class="btn btn-sm btn-primary" type="button" disabled>Aggiunto</button>
        <span class="d-block mt-1 text-muted">Disabled CTA S</span>
    </div>
</div>

<span class="mt-5 d-block text-muted text-uppercase">Secondary Buttons</span>
<hr class="mt-0" />

<div class="row">
    <div class="col-12 col-md-6 col-lg-4">
        <button class="btn btn-secondary btn-block btn-lg" type="button">Accedi Ora</button>
        <span class="d-block mt-1 text-muted">Enabled CTA XL</span>
    </div>
    <div class="col-12 col-md-6 col-lg-4">
        <button class="btn btn-secondary btn-block btn-lg" type="button" disabled>Accedi Ora</button>
        <span class="d-block mt-1 text-muted">Disabled CTA XL</span>
    </div>
</div>
<div class="row my-4">
    <div class="col-12 col-md-6 col-lg-4">
        <button class="btn btn-secondary btn-block" type="button">Accedi</button>
        <span class="d-block mt-1 text-muted">Enabled CTA L</span>
    </div>
    <div class="col-12 col-md-6 col-lg-4">
        <button class="btn btn-secondary btn-block" type="button" disabled>Accedi</button>
        <span class="d-block mt-1 text-muted">Disabled CTA L</span>
    </div>
</div>