<h2 class="mt-4" id="links">Links</h2>
<div class="row my-3">
    <div class="col-12 col-sm-6 col-md-3">
        <span class="text-muted text-uppercase">Base</span>
        <hr class="mt-0">
        <!-- BLOCK -->
        <div class="row mb-3">
            <div class="col">
                <a href="#">Link</a>
                <span class="d-block mt-1 text-muted">Primary</span>
            </div>
            <div class="col">
                <a class="font-body-sm" href="#">Link</a>
                <span class="d-block mt-1 text-muted">Small</span>
            </div>
        </div>
        <!-- /BLOCK -->
    </div>
</div>
