<h2 id="tabs">Tabs</h2>
<?php
$tabs = [
    [
        'id' => 'one',
        'label' => 'Active',
        'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque delectus esse magnam nostrum possimus quaerat, quo
    vel velit voluptate? Culpa doloribus harum incidunt obcaecati porro quaerat veritatis voluptatum! Magni, velit.</p>
<p>A, at culpa, dolore ducimus enim error fugiat neque nisi obcaecati omnis perspiciatis reiciendis repudiandae sed sint
    voluptatibus! Commodi eius hic libero rem! Fugit natus officiis, porro quaerat quia recusandae!</p><p>Adipisci atque
    consectetur consequatur dolores ea earum eligendi hic, laborum nam nihil obcaecati quia, ratione reiciendis rerum
    sed veniam vero voluptate! Accusamus ea expedita non pariatur quisquam suscipit unde, vero.</p><p>Dicta dolorum
    laudantium molestias voluptas. Asperiores, commodi consequatur culpa delectus, doloremque dolores hic ipsam magni
    maxime molestiae possimus quisquam ratione voluptatem. Aperiam minima minus molestias pariatur suscipit, temporibus
    unde veritatis.</p><p>Architecto cum cumque facilis inventore iste itaque libero maxime minus natus necessitatibus
    nesciunt provident quaerat quam saepe sint sunt velit veniam vero vitae, voluptatem. Facilis nobis omnis quod
    sapiente veniam?</p><p>Aliquid et ex in laboriosam magni molestiae obcaecati saepe sapiente totam voluptates.
    Aspernatur blanditiis, dignissimos eaque eum fugit id molestias nostrum qui quia, sapiente tempore temporibus.
    Accusantium corporis placeat voluptate.</p><p>Aliquam amet assumenda atque, aut culpa cupiditate dolorum earum eius
    fugit incidunt labore laboriosam magni minus molestiae nam pariatur placeat porro qui quod quos recusandae saepe
    sequi similique voluptas voluptatibus?</p><p>Dolorem error pariatur veniam! Accusantium alias amet assumenda at
    autem blanditiis cumque dolorem, est fugiat illum necessitatibus odit perspiciatis porro quae qui recusandae
    repellendus sed sint suscipit totam veniam veritatis.</p><p>Ab ad aliquid aspernatur beatae doloribus eveniet facere
    hic magni maxime minima, nobis similique voluptate. Beatae culpa eaque facere libero nam optio porro tempora tenetur
    totam veniam. Aliquid, doloribus, magni.</p><p>Aspernatur assumenda magnam odit optio possimus qui quo repellat. Aut
    delectus dolore dolorem fugit hic molestiae nulla obcaecati quos rem rerum? Accusantium alias, doloribus dolorum
    eaque id quidem reiciendis? Voluptatem.</p>'
    ],
    [
        'id' => 'two',
        'label' => 'Link',
        'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci optio sequi vero. Delectus eaque illo optio
    praesentium sint ut veniam.</p><p>Beatae deleniti doloribus ducimus earum harum in ipsa, laudantium officiis
    pariatur perspiciatis qui ratione repellat repellendus. Ipsam nam qui quos.</p><p>Culpa laborum laudantium maxime
    molestias, necessitatibus officia tempore voluptatibus? Animi aperiam dolores ea earum ipsum magnam magni molestias
    quod vero?</p><p>Assumenda corporis distinctio ipsa natus quidem, tempora velit vero! At debitis illum ipsum nemo
    odit quaerat saepe vel voluptas voluptatibus.</p><p>Fuga magnam perferendis porro provident ut? Ad alias autem eum
    facere ipsum non perferendis quam quas repudiandae suscipit? Culpa, unde!</p><p>A, ad consectetur, dolore, esse eum
    facilis impedit incidunt laborum nihil optio placeat quae quia repellendus sunt temporibus. Minus, veniam.</p><p>
    Enim, esse, natus. Atque, doloremque eaque earum harum id in iste itaque iusto molestiae optio provident quibusdam
    quod tempore tenetur.</p><p>Eos fuga ipsum labore! Dignissimos dolorem ratione reiciendis? Consequuntur deleniti
    distinctio fugiat in laborum magnam maiores, nobis pariatur quaerat velit.</p><p>Amet animi ex excepturi impedit
    mollitia, quidem suscipit. Atque delectus dolores excepturi possimus quia, recusandae rerum voluptate? Molestias
    quo, similique?</p><p>Aut corporis, culpa debitis deserunt ducimus eaque esse illum in incidunt iste labore,
    obcaecati possimus quam sed sit soluta suscipit?</p><p>Aspernatur dolore ea enim labore maxime nemo nisi odio
    quisquam soluta unde. Consequatur illum maxime voluptas! Amet asperiores aspernatur cumque?</p><p>Adipisci, animi
    eligendi eum minus molestiae molestias officia omnis optio reiciendis saepe sunt voluptas! Accusantium explicabo
    fuga quibusdam ullam vero.</p>'
    ],
    [
        'id' => 'three',
        'label' => 'Link',
        'content' => 'A assumenda doloribus, dolorum earum enim hic modi non soluta.'
    ],
    [
        'id' => 'four',
        'label' => 'Disabled',
        'content' => 'Ad aut deleniti earum fuga fugiat incidunt nam quia vel.'
    ],
    [
        'id' => 'five',
        'label' => 'Link',
        'content' => 'Dolore eaque error iste iusto maxime placeat quod, tempora! Quo!'
    ],
    [
        'id' => 'six',
        'label' => 'Link',
        'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, reprehenderit!'
    ],
    [
        'id' => 'seven',
        'label' => 'Link',
        'content' => 'Alias, sit temporibus. Accusantium aliquam earum expedita nisi quod tempora.'
    ],
    [
        'id' => 'eight',
        'label' => 'Link',
        'content' => 'Aspernatur itaque labore neque, placeat recusandae saepe tenetur! Eveniet, sequi?'
    ],
    [
        'id' => 'nine',
        'label' => 'Link',
        'content' => 'A distinctio dolorem ipsa nesciunt officiis quae quaerat quis voluptatum.'
    ],
    [
        'id' => 'ten',
        'label' => 'Link',
        'content' => 'Ad autem commodi deleniti dolores facilis incidunt libero quaerat repellat.'
    ]
];
?>

<span class="mt-4 d-block text-muted text-uppercase">Bootstrap</span>
<hr class="mt-0" />
<div class="tabs-bootstrap position-relative" id="sticky-tabs" data-mage-init='{"tabs":{ "openedState":"active", "disabled":[3], "disabledState": "disabled", "content":".tab-pane", "collapsibleElement":".nav-link", "trigger":".nav-link"}}'>
    <ul class="nav nav-tabs" role="tablist" data-mage-init='{ "dnaCarousel": { "middleWrapperClass":"overflow-visible" ,"responsive": {}, "autoWidth": true, "dots":false, "nav": false, "controls": false }}'>
        <?php foreach ($tabs as $i => $tab): ?>
            <li class="nav-item">
                <a data-toggle="tab" role="tab" href="#<?= $tab['id'] ?>_bootstrap" class="nav-link"><?= $tab['label'] ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="tab-content">
        <?php foreach ($tabs as $i => $tab): ?>
            <div class="tab-pane show active py-2" id="<?= $tab['id'] ?>_bootstrap" role="tabpanel" aria-labelledby="<?= $tab['id'] ?>_bootstrap-tab">
                <?= $tab['content'] ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<span class="mt-4 d-block text-muted text-uppercase">Magento</span>
<hr class="mt-0" />
<div class="product data items pt-1" data-mage-init='{"tabs":{"openedState":"active", "disabled":[3], "disabledState": "disabled"}}'>
    <?php foreach ($tabs as $i => $tab): ?>
        <?php $id = $tab['id'].'-magento'; ?>
        <div class="data item title"
             data-role="collapsible" id="tab-label-<?= $id ?>">
            <a class="data switch"
               tabindex="-1"
               data-toggle="trigger"
               href="#<?= $id ?>"
               id="tab-label-<?= $id ?>-title">
                <?= $tab['label'] ?>
            </a>
        </div>
        <div class="data item content"
             aria-labelledby="tab-label-<?= $id ?>-title" id="<?= $id ?>" data-role="content">
            <?= $tab['content'] ?>
        </div>
    <?php endforeach; ?>
</div>


<br class="mb-5"/>

