<h2 id="typography">Typography</h2>
<div class="row">
    <div class="col-12 col-md-6">
        <span class="text-muted text-uppercase">HTML</span>
        <hr class="mt-0" />
        <h1>H1 - Lorem ipsum.</h1>
        <h2>H2 - Beatae, sequi!</h2>
        <h3>H3 - Dolorum, incidunt.</h3>
        <h4>H4 - Ea, id!</h4>
        <h5>H5 - Beatae, similique!</h5>
        <h6>H6 - Blanditiis, ex!</h6>
    </div>
    <div class="col-12 col-md-6">
        <span class="text-muted text-uppercase">CSS CLASSES</span>
        <hr class="mt-0" />
        <div class="h1">H1 - Lorem ipsum.</div>
        <div class="h2">H2 - Beatae, sequi!</div>
        <div class="h3">H3 - Dolorum, incidunt.</div>
        <div class="h4">H4 - Ea, id!</div>
        <div class="h5">H5 - Beatae, similique!</div>
        <div class="h6">H6 - Blanditiis, ex!</div>
    </div>
</div>

<div class="row my-3">
    <div class="col-12 col-lg-2">Body</div>
    <div class="col-12 col-lg-10">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea error placeat repudiandae! A at commodi delectus
        eligendi, excepturi fugiat minima porro sed sunt voluptatem! Beatae delectus eligendi hic, impedit labore minus nemo
        nostrum nulla pariatur porro quia rem similique tenetur velit veniam! Accusamus aliquam aspernatur atque dolore
        doloremque earum enim eum excepturi illum, odit officiis qui quibusdam quo sed soluta veritatis vitae, voluptatem.
        Culpa enim fugit libero quaerat! Ad aspernatur assumenda at aut, blanditiis, cum delectus deleniti distinctio
        excepturi facere, libero molestiae nesciunt odio pariatur quae quas quis rerum sunt tenetur totam! Accusamus
        consequuntur debitis deleniti deserunt dolorum eius minus natus ut? Ab aliquid autem commodi consequatur dignissimos
        eaque eligendi enim eum eveniet facere fuga illum inventore ipsa ipsam labore libero modi odit, optio perspiciatis
        porro quidem ratione sequi sint? Libero molestiae, nesciunt omnis tempora voluptatem voluptates!</div>
</div>
<div class="row my-3 font-sm">
    <div class="col-12 col-lg-2">Body sm (.font-sm)</div>
    <div class="col-12 col-lg-10">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea error placeat repudiandae! A at commodi delectus
        eligendi, excepturi fugiat minima porro sed sunt voluptatem! Beatae delectus eligendi hic, impedit labore minus nemo
        nostrum nulla pariatur porro quia rem similique tenetur velit veniam! Accusamus aliquam aspernatur atque dolore
        doloremque earum enim eum excepturi illum, odit officiis qui quibusdam quo sed soluta veritatis vitae, voluptatem.
        Culpa enim fugit libero quaerat! Ad aspernatur assumenda at aut, blanditiis, cum delectus deleniti distinctio
        excepturi facere, libero molestiae nesciunt odio pariatur quae quas quis rerum sunt tenetur totam! Accusamus
        consequuntur debitis deleniti deserunt dolorum eius minus natus ut? Ab aliquid autem commodi consequatur dignissimos
        eaque eligendi enim eum eveniet facere fuga illum inventore ipsa ipsam labore libero modi odit, optio perspiciatis
        porro quidem ratione sequi sint? Libero molestiae, nesciunt omnis tempora voluptatem voluptates!</div>
</div>
<br class="mb-5"/>
